version: '3.9'
services:
  backend:
    build: ./
    container_name: app_backend
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=localhost
      - DB_NAME=softeo_database
      - DB_PASS=123456
      - DB_PORT=3306
      - DB_USER=root
      - PORT=3001
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: softeo_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
